apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: monitoring
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/port:   '9090'
spec:
  selector:
    app: prometheus-server
  ports:
    - name: web
      port: 9090              # Service port (inside cluster)
      targetPort: 9090        # Pod container port
      nodePort: 30914         # Fixed NodePort on the node
  type: NodePort
