name: "Deploy Prometheus with Terraform"

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

  

      # Step 4: Export kubeconfig
      - name: Export KUBECONFIG
        run: |
          mkdir -p $HOME/.kube
          kind get kubeconfig > $HOME/.kube/config
          chmod 600 $HOME/.kube/config

     
      # Step 7: Terraform Validate
      - name: Terraform Validate
        run: terraform validate

      # Step 8: Terraform Plan
      - name: Terraform Plan
        run: terraform plan -out=tfplan

      # Step 9: Terraform Apply (only on main branch)
      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve tfplan
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }}
